import Head from 'next/head'
import SimpleSlider from '../components/SimpleSlider'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Edvora App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </Head>
      <SimpleSlider />
      <footer className={styles.footer}>
        <a
          href="https://rahul-wp.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Rahul
        </a>
      </footer>
    </div>
  )
}
